### ISSUE TITLE
Docker image doesn't run in new Macs with M1 (ARM64 based)

### ISSUE THREAD

**Issue by OneComputerGuy** [blackboard/BBDN-UEF-Python#3]
While trying to run the docker image, the following errors are received:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[2021-04-22 18:51:44 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2021-04-22 18:51:44 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2021-04-22 18:51:44 +0000] [1] [INFO] Using worker: threads
[2021-04-22 18:51:44 +0000] [11] [INFO] Booting worker with pid: 11
[2021-04-22 18:51:44 +0000] [13] [INFO] Booting worker with pid: 13
[2021-04-22 18:51:44 +0000] [15] [INFO] Booting worker with pid: 15
[2021-04-22 18:51:44 +0000] [17] [INFO] Booting worker with pid: 17
[2021-04-22 18:51:45 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 1, in <module>
    from app import app
  File "/app/app.py", line 27, in <module>
    from pylti1p3.contrib.flask import FlaskOIDCLogin, FlaskMessageLaunch, FlaskRequest, FlaskCacheDataStorage
  File "/usr/local/lib/python3.8/site-packages/pylti1p3/contrib/flask/__init__.py", line 3, in <module>
    from .message_launch import FlaskMessageLaunch
  File "/usr/local/lib/python3.8/site-packages/pylti1p3/contrib/flask/message_launch.py", line 1, in <module>
    from pylti1p3.message_launch import MessageLaunch
  File "/usr/local/lib/python3.8/site-packages/pylti1p3/message_launch.py", line 10, in <module>
    from jwcrypto.jwk import JWK
  File "/usr/local/lib/python3.8/site-packages/jwcrypto/jwk.py", line 14, in <module>
    from six import iteritems
ModuleNotFoundError: No module named 'six'
```

The error repeats a few times and then the image exists. Uncertain if there's an ARM64 based image of Flask we can use for M1s

**Comment by OneComputerGuy** [comment]
Issue is solved by adding six==1.15.0 to the package.json file.
